- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/pr-commands.yaml
- DESCRIPTION
- inst/WORDLIST
- tests/testthat.R
- tests/testthat/parsnip-helper-objects.R
- tests/testthat/test-aaa-spark-install.R
- tests/testthat/test-data-descriptors-spark.R
- tests/testthat/test-encodings-glmnet.R
- tests/testthat/test-encodings-randomForest.R
- tests/testthat/test-encodings-ranger.R
- tests/testthat/test-engine-parameters-c5.R
- tests/testthat/test-engine-parameters-earth.R
- tests/testthat/test-engine-parameters-randomForest.R
- tests/testthat/test-engine-parameters-ranger.R
- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
- tests/testthat/test-glmnet-tidy.R
- tests/testthat/test-parsnip-boost-tree-spark.R
- tests/testthat/test-parsnip-linear-reg-spark.R
- tests/testthat/test-parsnip-logistic-reg-spark.R
- tests/testthat/test-parsnip-multinom-reg-spark.R
- tests/testthat/test-parsnip-rand-forest-spark.R
- tests/testthat/test-stan-linear.R
- tests/testthat/test-stan-logistic.R
This is to move spark testing out of `parsnip`. 
Currently not testing on Windows, only macOS. Fails with error: 
```
> ## -----------------------------------------------------------------------------
> 
> library(sparklyr)
Attaching package: 'sparklyr'
The following object is masked from 'package:purrr':
invoke
> 
> if (.Platform$OS.type == "windows") {
+   spark_install_winutils("2.4")
+   sparklyr::spark_install(verbose = TRUE, version = "2.4", hadoop_version = "2.7")
+ } else {
+   sparklyr::spark_install(verbose = TRUE, version = "2.4")
+ }
Installing winutils...
trying URL 'https://github.com/steveloughran/winutils/raw/master/hadoop-2.6.0/bin/winutils.exe'
Content type 'application/octet-stream' length 108032 bytes (105 KB)
================================================== …
```
> Spark configuration and tests from parsnip

- tests/testthat/test-mars-tuning.R
This PR adds one test file that sets up and tunes a MARS classification model. The main motivation is that this particular model has a mix of different number of submodels per model (including zero submodels), and tests the changes made in tidymodels/tune#250. I'm pretty sure these tests will fail until that PR is merged, and then will fail for the CRAN GH action until tune makes it to CRAN next.
> Add test for mars(), for submodel/no submodel case

- tests/testthat/test-mars-tuning.R
This expands the tests for the tuning submodel case to make sure that predictions are unique per row and config, i.e. that `.config` was set correctly. This PR addresses tidymodels/tune#258.
I did find one failure locally here, but I don't _think_ it's related:
```
test-encodings-glmnet.R:80: failure: workflows
`predict(parsnip_wflow_fit, ames %>% select(Year_Built, Alley))` threw an error.
Message: error in evaluating the argument 'x' in selecting a method for function 'as.matrix': Cholmod error 'X and/or Y have wrong dimensions' at file ../MatrixOps/cholmod_sdmult.c, line 90
Class:   simpleError/error/condition
Backtrace:
1. testthat::expect_error(...) tests/testthat/test-encodings-glmnet.R:80:2
22. base::.handleSimpleError(...)
23. base:::h(simpleError(msg, call))
```
> Check that submodel predictions are unique per .config

- .github/workflows/GH-R-CMD-check.yaml
- DESCRIPTION
- tests/testthat.R
- tests/testthat/test-S3-registration.R
- tests/testthat/test-encodings-glmnet.R
- tests/testthat/test-encodings-randomForest.R
- tests/testthat/test-encodings-ranger.R
- tests/testthat/test-engine-parameters-c5.R
- tests/testthat/test-engine-parameters-earth.R
- tests/testthat/test-engine-parameters-randomForest.R
- tests/testthat/test-engine-parameters-ranger.R
- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
- tests/testthat/test-glmnet-poisson.R
- tests/testthat/test-glmnet-tidy.R
- tests/testthat/test-mars-tuning.R
- tests/testthat/test-parallel-psock.R
- tests/testthat/test-parallel-seeds.R
- tests/testthat/test-spark-aaa-install.R
- tests/testthat/test-spark-boost-tree.R
- tests/testthat/test-spark-data-descriptors.R
- tests/testthat/test-spark-linear-reg.R
- tests/testthat/test-spark-logistic-reg.R
- tests/testthat/test-spark-multinom-reg.R
- tests/testthat/test-spark-rand-forest.R
- tests/testthat/test-stan-linear.R
- tests/testthat/test-stan-logistic.R
- tests/testthat/test-stan-poisson.R
This PR makes some changes to get the GH testing up and running.
After these change, I am still seeing some unexpected results/breakages that need to be addressed:
- The S3 methods for recipe steps for `required_pkgs()` are not working, such as `required_pkgs.step_pls()`. I can reproduce this locally. The other S3 methods for `required_pkgs()` (like for a recipe, a parsnip model, a workflow) _are_ working.
- Some tests are being skipped for poissonreg and discrim because of semantic versioning issues. 
```
── Skipped tests  ────────────────────────────
● utils::packageVersion("discrim") <= "0.1.0.9000"  is TRUE (1)
● utils::packageVersion("poissonreg") < "0.1.0"  is TRUE (1)
```
The current GitHub versions of these packages in the main branch are _before_ these versions, so they are …
> Massage GH testing

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/test-parallel-psock.R
- tests/testthat/test-parallel-seeds.R
This PR adds back in the tests for parallel processing on Windows that were removed in #10.
> Add parallel tests for Windows back in

- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
Related to tidymodels/parsnip#382
This PR adds tests to check that predictions for the `x`/`y` interface of glmnet are the same no matter what order the columns come in.
> Test for glmnet x/y column order predictions

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/spark-R-CMD-check.yaml
- DESCRIPTION
- tests/testthat/test-sparse-glmnet.R
Closes tidymodels/tidymodels#42
This PR adds tests for the sparse and matrix `composition` in recipes through fitting and tuning.
> Add tests for composition support

- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
Related to tidymodels/parsnip#395
This PR tests the single observation case for glmnet models. It will fail until the parsnip PR is merged in.
> Test predicting single observation for glmnet models

- tests/testthat/test-spark-data-descriptors.R
This PR adds back in the test for data descriptors on Spark removed in #10.
This will currently fail on Ubuntu because of backticks in the abort in parsnip. It comes from here:
```
> parsnip:::get_descr_form(compounds ~ class, data = hpc_descr)
$.cols
function () 
all_preds
<bytecode: 0x7fc264a0ddc8>
<environment: 0x7fc2828b4868>
$.preds
function () 
length(f_term_labels)
<bytecode: 0x7fc264a0dc78>
<environment: 0x7fc2828b4868>
$.obs
function () 
obs
<bytecode: 0x7fc264a13aa8>
<environment: 0x7fc2828b4868>
$.lvls
function () 
y_vals
<bytecode: 0x7fc264a13958>
<environment: 0x7fc2828b4868>
$.facts
function () 
factor_pred
<bytecode: 0x7fc264a13808>
<environment: 0x7fc2828b4868>
$.dat
function () 
abort("Descriptor `.dat()` not defined for Spark.")
<bytecode: 0x7fc264a134f8>
<environment: …
```
> Add back in data descriptor test for Spark

- tests/testthat/test-S3-registration.R
This PR addresses the recent changes in workflows + tune to `required_pkgs()` that caused failures here. It just switched the order that the required packages came through, which we don't need to explicitly test.
> Test more robustly for required packages

- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
Related to tidymodels/parsnip#485
This PR updates our glmnet tests for the new requirements around `penalty` in the glmnet engine.
> Update glmnet tests

- tests/testthat/_snaps/tunable.md
- tests/testthat/helper-tunable.R
- tests/testthat/test-tunable.R
the methods are for the following objects: `recipe`, a model spec (`boost_tree`), and `workflow`
> add tests for `tunable()` methods

- tests/testthat/test-glmnet-linear.R
Related to tidymodels/parsnip#625
> Add test for `form_xy()` character outcome errors

- tests/testthat/test-stacks-columns.R
Addresses the current failing tests for stacks—more info on tidymodels/stacks#99. :)
> bump stacks version

- .github/workflows/GH-R-CMD-check.yaml
At first, the current Action installs the correct parsnip version 284252b with case weights: https://github.com/tidymodels/extratests/runs/6210633506?check_suite_focus=true#step:6:69
but then it’s "updated" to the main branch version 80ebaa8 later on: https://github.com/tidymodels/extratests/runs/6210633506?check_suite_focus=true#step:6:267
I was able to reproduce the errors in those above checks by installing parsnip from the github main branch and leaving all other package versions as instructed in the current draft of the case weights blog post. We'll see if this does the trick to fix it!
> install devel parsnip last

- .github/workflows/GH-R-CMD-check.yaml
Since the [case weights branch of recipes](https://github.com/tidymodels/recipes/pull/835) was merged, it can no longer be installed and it rolls back to the CRAN version of recipes.
> no more case weights branch for recipes

- tests/testthat/test-spatialsample-tuning.R
This PR adds a test to make sure that `tune_grid` works with resampled `sf` objects, and that the exclusion buffer (assigning values to neither assessment nor analysis) is respected.
> Tune with sf objects

- tests/testthat/_snaps/parsnip-case-weights.md
- tests/testthat/test-parsnip-case-weights.R
This PR changes the tests for `proportional_hazards()`, which look at the engine fit.
I changed where the engine fit is saved in the parsnip object in the dev version of censored, so the new tests run conditional on the dev version - so that the tests for the (current) CRAN version don't fall.
> Update tests for `proportional_hazards()`

- DESCRIPTION
- tests/testthat/test-stacks-tuning.R
`tune_race_anova()` would be the only tuning method that I'd imagine stacks might be especially sensitive to, so this adds tests to make sure that we correctly handle candidates based on whether they were completely resampled. Otherwise, this just makes sure we run through one worked example with `tune_grid()`, `tune_bayes()`, `tune_race_anova()`, `tune_sim_anneal()`, and `tune_win_loss()`, and check that the outputs have the classes we'd expect.
> test stacks with several tuning methods

- tests/testthat/test-spatialsample-tuning.R
This PR _hopefully_ fixes extratests by changing both spatialsample tests to use sf objects, now that we're putting non-spatial CV entirely in rsample's hands.
I made this a relatively minimal change, because I like testing two different types of resampling. These tests do somewhat duplicate each other now, though, and we can cut the first test entirely if that feels better.
> Change non-spatial tuning test

- tests/testthat/_snaps/glmnet-multinom.md
- tests/testthat/test-glmnet-multinom.R
Similar to https://github.com/tidymodels/extratests/pull/66 and #68
The best way to read the changes is probably again commit-by-commit.
The tests are similar in structure to those for `linear_reg()` and `logistic_reg()` and follow the ideas laid out in https://github.com/tidymodels/extratests/pull/66 and #68.
> glmnet tests for `multinom_reg()`

- tests/testthat/_snaps/glmnet-poisson.md
- tests/testthat/test-glmnet-poisson.R
Similar to #66, #68, and #69
The best way to read the changes is probably again commit-by-commit.
The tests are similar in structure to those for `linear_reg()`, `logistic_reg()` and `multinom_reg()` follow the ideas laid out in #66, #68, and #69.
The tests for `multi_predict()` should be added when closing https://github.com/tidymodels/poissonreg/issues/63.
The second expectation of `test_that("error traps", {})` should be updated when closing https://github.com/tidymodels/parsnip/issues/757.
> glmnet tests for `poisson_reg()`

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
These are tests for https://github.com/tidymodels/parsnip/pull/863
> glmnet engines for `logistic_reg()` and `multinomial_reg()` respect the penalty from the spec

- tests/testthat/_snaps/parsnip-case-weights.md
- tests/testthat/test-parsnip-case-weights.R
`poisson_reg()` now also safe-guards Ridge regression, so we do expect to see `lamda` there instead of `path_values`
https://github.com/tidymodels/parsnip/pull/880
> Fix snapshot for `poisson_reg()`

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/glmnet-linear.md
- tests/testthat/_snaps/glmnet-logistic.md
- tests/testthat/_snaps/glmnet-multinom.md
- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
tests for https://github.com/tidymodels/parsnip/pull/900
> glmnet `multi_predict()`: tighten tests for checks on prediction type

- tests/testthat/_snaps/sparse-glmnet.md
- tests/testthat/test-sparse-glmnet.R
We have checks for both CRAN versions and dev versions right? That means this will pass with CRAN hardhat and fail with dev hardhat until the dev version goes to CRAN, because I've improved on the error message here.
I don't think there is much we can do about that.
> Use a snapshot test to check the hardhat error

- tests/testthat/test-yardstick-known-selections.R
`yardstick:::in_tuning_env()` looks to the `defer()`red `rlang::ns_env("tune")$tune_env$progress_active` to determine whether to cache known selections. This flag is only set to `TRUE` by tune when running outside of testthat, see [here](https://github.com/tidymodels/tune/blob/2a6332c35e32b4416ce868815884d8b26c3ff772/R/logging.R#L102-L108).
> skip known selections test in testthat

- tests/testthat/_snaps/parsnip-survival-censoring-model.md
- tests/testthat/test-parsnip-survival-censoring-model.R
This PR reworks the tests to
- use more specific expectations like `expect_s3_class()`
- groups setup and expectations closer together when they are in the same test_that() call
- splits expectations into more test_that() calls to make the description of the test more specific
- allows missing values in the test data so that we notice if that ever were not to work again and because having it in there typically signals that the function cannot deal with missing values
> Refine tests for parsnip-survival-censoring-model

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/parsnip-survival-censoring-weights.md
- tests/testthat/test-parsnip-survival-censoring-weights.R
test update for https://github.com/tidymodels/parsnip/pull/972
> `.check_censor_model()` now errors for models without "censored regression" mode

- tests/testthat/_snaps/parsnip-model-formula.md
- tests/testthat/test-engine-parameters-c5.R
- tests/testthat/test-engine-parameters-earth.R
- tests/testthat/test-engine-parameters-randomForest.R
- tests/testthat/test-engine-parameters-ranger.R
- tests/testthat/test-parsnip-model-formula.R
- tests/testthat/test-stacks-columns.R
- tests/testthat/test-stacks-tuning.R
- tests/testthat/test-stan-linear.R
- tests/testthat/test-stan-logistic.R
- tests/testthat/test-stan-poisson.R
- tests/testthat/test-tune_bayes.R
This is a first pass at #124 
This PR wraps  `suppressMessages()` around several calls to `tune_bayes()` and friends in cases where we don't do anything with the messages anyway. 
Also in this PR: removing some `library(rlang)` calls that are not needed anymore and resulted in a couple of lines of 
> The following object is masked from
> Less noise

- tests/testthat/test-survival-workflows.R
As the title says, this PR starts the project of adding tests for censored models used in workflows
> initial survival workflows tests

- tests/testthat/test-survival-workflows.R
This PR aims to close https://github.com/tidymodels/extratests/issues/111.
With this PR, we are now testing a `proportional_hazards()` model in a workflow where we
- use a formula with `add_formula()`
- use a model formula passed to `add_model()` this formula contains `strata()`
- use variables with `add_variables()`
- use a recipe with `add_recipe()`
We are testing that we 
- can use `fit()`
- can use `predict()`
- with `type = "time"` (default)
- with `type = "survival"`
> Improve test survival workflows

- tests/testthat/test-parsnip-survival-censoring-weights.R
- tests/testthat/test-parsnip-survival-standalone.R
Light touch-up on #131 
The issue was that names popped up in the censoring weights for 1 observation with 1 eval time https://github.com/tidymodels/parsnip/issues/1023.
The solution was to unname the elements coming out of `.extract_surv_time()` and `.extract_surv_status()` https://github.com/tidymodels/parsnip/pull/1024
In #131 we added tests on `.parsnip:::graf_weight_time_vec()`, this PR adds tests on `.extract_surv_time()` and `.extract_surv_status()` since those were the functions modified in the solution.
> Follow-up to #131

- tests/testthat/_snaps/parsnip-survival-censoring-model.md
- tests/testthat/test-parsnip-survival-censoring-model.R
Related to https://github.com/tidymodels/parsnip/pull/1037
> add tests for empty dots in predict.censoring_model_reverse_km()

- tests/testthat/_snaps/parsnip-survival-censoring-weights.md
- tests/testthat/test-parsnip-survival-censoring-weights.R
result of tidymodels/parsnip#1038 and tidymodels/workflows#213
> add skip for method moved to workflows

- DESCRIPTION
Closes #171, hopefully?
Note that this means that the "CRAN" checks will install dev aorsf.
> add aorsf Remote

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/survival-tune_race_anova.md
- tests/testthat/_snaps/survival-tune_race_win_loss.md
- tests/testthat/test-survival-tune_race_anova.R
- tests/testthat/test-survival-tune_race_win_loss.R
Tests for tidymodels/finetune#94.
> ensure racing functions warn informatively with unneeded `eval_time`

- tests/testthat/_snaps/censored-case-weights.md
- tests/testthat/test-censored-case-weights.R
to close https://github.com/tidymodels/extratests/issues/160
After a LOT of dead ends. I figured it out! `library(baguette)` is being run in a `test_that()` in a previous test file, which then trigger some `parsnip::set_model_arg()` calls from {baguette}s `.onload()`. Since we started running only some tests, we are no longer triggering the `library(baguette)` call.
This PR fixes that by added a `library(baguette)` in the affected test. I added an issue $186 so we can think about how we can deal with this is a better way.
``` r
library(tidymodels)
library(censored)
#> Loading required package: survival
make_cens_wts <- function() {
data(time_to_million, package = "censored", envir = rlang::current_env())
set.seed(1)
time_to_million <- time_to_million[1:100, c("time", "event", …
```
> Fix mismatch in bag_tree fit call

- tests/testthat/test-survival-tune-int-pctl.R
Units tests for tidymodels/tune#818
Uses a variety of objects, models, and resampling methods that create `tune_results` objects.
> percentile interval tests for survival analysis

- tests/testthat/test-survival-augment.R
This was testing that `augment()` would not trip up if an engine didn't provide predictions with `type = "time"` or `type = "survival"` but aorsf was the only one missing. Now* all engines for all models in censored provide predictions for those two types.
*Now = after https://github.com/tidymodels/censored/pull/308 is merged
> Remove test on augment() on aorsf models

- tests/testthat/helper-objects.R
We were getting sooooo many of these: 
> Warning message:
> In sparklyr::spark_install_find() :
>   The Spark version specified may not be available.
> Please consider running `spark_available_versions()` to list all known available Spark versions.
> stop excessive warnings when checking for spark

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/survival-workflow-set.md
- tests/testthat/test-survival-workflow-set-fit_best.R
Mirrors [the tests for `fit_best.tune_results()`](https://github.com/tidymodels/extratests/blob/def7031b67ba1c615e3c3fe12f15d6edb1cc3cd7/tests/testthat/test-survival-fit_best.R) as closely as possible, switching out model + preprocessor with a workflowset containing the same!
Tests for tidymodels/workflowsets#144.
> test `fit_best.workflow_set()` with survival

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/test-survival-tune-int-pctl.R
For https://github.com/tidymodels/tune/issues/856: to show that the subsetting of `eval_time` still works after removing the `eval_time` argument from lower level functions like `.estimate_metrics()`.
Plan is to have the CI run through, then again with the branch with changes.
> Add test on `int_pctl()` for survival models with a subset of evaluation times

- tests/testthat/test-baguette-case-weights.R
Before this PR:
```
✔ |   1      7 | baguette-case-weights [1898.5s] 
```
(31 minutes!)
After this PR:
```
✔ |          7 | baguette-case-weights [1.7s] 
```
> speed up baguette case weights test

- .github/workflows/GH-R-CMD-check.yaml
Closes #202. 
In the cases where we have known circular dependencies, we can just pull the offending packages back into their own `pkg_install()` lines temporarily.
> address dev package install ordering

- .github/workflows/keep-alive.yaml
~~Uses [gautamkrishnar/keepalive-workflow](https://github.com/gautamkrishnar/keepalive-workflow) to keep Actions alive after a period of inactivity by pushing a dummy commit to main. Runs nightly, but only pushes after 45 days of inactivity. Based on [this example](https://github.com/gautamkrishnar/keepalive-workflow?tab=readme-ov-file#dummy-commit-keepalive-workflow-for-github-actions-users).~~
EDIT: rewritten to avoid external dependency. Instead of pushing after 45 days of inactivity, just pushes once a month regardless of repo activity.
> use cron job to keep Actions alive after inactivity

- tests/testthat/_snaps/survival-tune-show-best.md
- tests/testthat/test-engine-parameters-ranger.R
- tests/testthat/test-survival-tune-show-best.R
Closes #217, related to https://github.com/tidymodels/tune/pull/919.
> update snapshots with space-filling grids

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- DESCRIPTION
- extratests.Rproj
> temporary solution regarding dimRed

- tests/testthat/test-engine-parameters-ranger.R
With changes to the `inclusive` data for a numeric parameter, the CRAN version of dials chokes on two specific tests (the devel version has a fix). 
This PR updates the test to change the parameter range to stop the failure. The change does not alter the intent of the unit test (for tuning engine parameters), just side-steps the short-term issue of zero values for the `regularization.factor` argument to `ranger()`
> changes for CRAN dials for regularization.factor

- tests/testthat/test-glmnet-tidy.R
Tests for tidymodels/parsnip#1261
Uses the same test case in that issue
> check glmnet penalty range

- tests/testthat/_snaps/survival-tune-autoplot.md
- tests/testthat/_snaps/survival-tune_race_anova.md
- tests/testthat/_snaps/survival-tune_race_win_loss.md
- tests/testthat/test-survival-tune-autoplot.R
- tests/testthat/test-survival-tune_race_anova.R
- tests/testthat/test-survival-tune_race_win_loss.R
Updating ggplot2 object tests to use `get_labels()`. 
Tests will still fail for unrelated reasons (e.g. column order changes etc) on GH tests but these are needed
> ggplot2::get_labels()

- tests/testthat/helper-objects.R
- tests/testthat/test-survival-augment.R
- tests/testthat/test-survival-fit-resamples.R
- tests/testthat/test-survival-last-fit.R
- tests/testthat/test-survival-tune-autoplot.R
- tests/testthat/test-survival-tune-bayes.R
- tests/testthat/test-survival-tune-grid.R
- tests/testthat/test-survival-tune-int-pctl.R
- tests/testthat/test-survival-tune-sa.R
- tests/testthat/test-survival-tune_race_anova.R
- tests/testthat/test-survival-tune_race_win_loss.R
- tests/testthat/test-survival-workflow-set.R
- tests/testthat/test-survival-workflows.R
- tests/testthat/test-workflows-survival-augment.R
The survival tests had many ptypes and vectors of column names that failed once we changed the column order. 
We might want to make a time-based skip to amend these once we are nearly done to make them sensitive to order, but I don't think that now is the time for that action. Alternatively, we can augment with some specific tests that lock down specific column orderings.
> making some tests insensitive to column order, survival tests
