- .github/workflows/GH-R-CMD-check.yaml
- DESCRIPTION
- tests/testthat/test-parallel-psock.R
> unit tests for recipes-adjacent packages

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/spark-R-CMD-check.yaml
- README.Rmd
- README.md
- tests/testthat.R
- tests/testthat/test-spark-aaa-install.R
- tests/testthat/test-spark-boost-tree.R
- tests/testthat/test-spark-data-descriptors.R
- tests/testthat/test-spark-linear-reg.R
- tests/testthat/test-spark-logistic-reg.R
- tests/testthat/test-spark-multinom-reg.R
- tests/testthat/test-spark-rand-forest.R
This PR works toward separating out the Spark tests so the main tests in this repo can run faster and have less complex installation.
> Move Spark tests

- tests/testthat/test-recipes-varying.R
This PR is related to tidymodels/recipes#635
> Add keep_original_cols to varying() tests

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/spark-R-CMD-check.yaml
To avoid failures like the [recent problem with a package failing to get built when it is new on CRAN](https://github.com/tidymodels/extratests/runs/1985069095?check_suite_focus=true)
> Switch to pak for package installation

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/spark-R-CMD-check.yaml
> Try ubuntu-18.04, plus devel with special user agent

- .github/workflows/GH-R-CMD-check.yaml
- DESCRIPTION
- tests/testthat/test-spatialsample-tuning.R
> Test that we can tune with spatialsample folds

- tests/testthat/test-butcher-recipes.R
Related to tidymodels/butcher#208
> Check that butchered recipes can `bake()`

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/spark-R-CMD-check.yaml
- DESCRIPTION
Uses V2 GHA
Also avoids pillar issue with `scale_type()`.
> GHA update 2022 01

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/spark-R-CMD-check.yaml
- tests/testthat/test-stacks-columns.R
Closes #48 
- Skip stacks tests and test against dev stacks in the GH workflow
- Remove XML since themis (we think?) no longer uses it
- Call `sudo apt-get update` to fix broken PPAs (this is the advice we got from the error output in the workflow and from Gabor)
> Apply various fixes to pass again

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/spark-R-CMD-check.yaml
update to 20.04 because the 18.04 runner was removed
> Update Ubuntu version for GHA

- DESCRIPTION
- tests/testthat/test-tunable.R
I'll park this until the next tune version is released.
> more specific tunable tests

- tests/testthat/test-sparse-glmnet.R
> update tests to reflect changes in recipes now returning integers

- tests/testthat/_snaps/glmnet-poisson.md
- tests/testthat/test-glmnet-poisson.R
test for https://github.com/tidymodels/parsnip/pull/860
> `poisson_reg(engine = "glmnet")` requires a `penalty` value

- tests/testthat/_snaps/glmnet-logistic.md
- tests/testthat/_snaps/glmnet-multinom.md
- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
This PR applies the test ideas that surfaced in the overhaul of the glmnet tests to all model types.
> streamlining glmnet test aspects

- DESCRIPTION
- tests/testthat/_snaps/survival-helpers.md
- tests/testthat/test-survival-helpers.R
additional unit tests for tidymodels/parsnip#893
> survival helpers in parsnip

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
tests for https://github.com/tidymodels/parsnip/pull/890
> tests for glmnet models with base-R families

- tests/testthat/_snaps/glmnet-logistic.md
- tests/testthat/_snaps/glmnet-multinom.md
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
Related to tidymodels/parsnip#912.
> update snaps with new parsnip `newdata` check helper

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/pr-commands.yaml
- .github/workflows/spark-R-CMD-check.yaml
This PR just updates the Github Actions
> Spring Cleaning 2023

- .github/workflows/GH-R-CMD-check.yaml
> Clean up install of dev versions

- DESCRIPTION
- tests/testthat/_snaps/censor-probs.md
- tests/testthat/test-censor-probs.R
For changes in tidymodels/parsnip#855
Depends on the most recent dev version of parsnip (1.0.3.9001)
> unit tests for censoring probabilities

- tests/testthat/test-yardstick-known-selections.R
PR 2/2: tests for https://github.com/tidymodels/yardstick/pull/428.
> test yardstick known selection caching

- tests/testthat/test-recipes-nnmf_sparse.R
As @simonpcouch correctly found, this is related to https://github.com/tidymodels/recipes/pull/1144. :slightly_smiling_face:
> update tibble test about step_nnmf_sparse()

- tests/testthat/_snaps/parsnip-survival-standalone.md
- tests/testthat/test-parsnip-survival-standalone.R
to go with https://github.com/tidymodels/parsnip/pull/973
> add test for `.time_as_binary_event()`

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/survival-augment.md
- tests/testthat/test-survival-augment.R
Related to https://github.com/tidymodels/parsnip/pull/991
> test that augment() gives nice error for missing eval_time

- .github/workflows/GH-R-CMD-check.yaml
follow-up to https://github.com/tidymodels/extratests/pull/103
> fix remote for parsnip

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/parsnip-model-formula.md
- tests/testthat/test-parsnip-model-formula.R
Related to tidymodels/parsnip#1015.
> test parsnip messaging re: model formulas

- .github/workflows/CRAN-R-CMD-check.yaml
- .github/workflows/GH-R-CMD-check.yaml
- .github/workflows/spark-R-CMD-check.yaml
This will allow us to trigger GHA runs manually instead of having to push/PR. :)
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch
> enable triggering GHA on `workflow_dispatch`

- tests/testthat/test-parsnip-survival-censoring-weights.R
Taken from the parsnip PR and added here.
> unit tests for tidymodels/parsnip#1024

- tests/testthat/test-butcher-recipes.R
- tests/testthat/test-censored-case-weights.R
- tests/testthat/test-discrim-case-weights.R
- tests/testthat/test-encodings-glmnet.R
- tests/testthat/test-glmnet-tidy.R
- tests/testthat/test-parallel-psock.R
- tests/testthat/test-parallel-seeds.R
- tests/testthat/test-parsnip-case-weights.R
- tests/testthat/test-parsnip-extension-messaging.R
- tests/testthat/test-parsnip-survival-censoring-model.R
- tests/testthat/test-parsnip-survival-censoring-weights.R
- tests/testthat/test-recipes-nnmf_sparse.R
- tests/testthat/test-rules-case-weights.R
- tests/testthat/test-spark-boost-tree.R
- tests/testthat/test-spark-data-descriptors.R
- tests/testthat/test-spark-linear-reg.R
- tests/testthat/test-spark-logistic-reg.R
- tests/testthat/test-spark-rand-forest.R
- tests/testthat/test-survival-augment.R
Since we are already working here a lot, i took some time to make it a little less noisy
> add suppressPackageStartupMessages() to packages

- tests/testthat/test-survival-tune-race.R
capturing the information closer to the code
> comments from #134 for context

- tests/testthat/test-parsnip-survival-standalone.R
tests for https://github.com/tidymodels/parsnip/pull/1027
(i know i wasn't following the proper way, i forgot 😓 )
> add tests of parsnip:::.extract_surv_time() for 1 length input

- tests/testthat/test-survival-tune-eval-time-attribute.R
Merge after tidymodels/tune#767 and tidymodels/finetune#165 are merged.
> retain eval_time for survival models

- tests/testthat/_snaps/survival-fit-resamples.md
- tests/testthat/test-survival-fit-resamples.R
Some of these changes are worth considering. I'm going to open another issue for that but this PR is intended to remove failures here in the meantime so that we see more easily if we break anything bigger than snapshots of warnings/errors.
Link to related tune PR: https://github.com/tidymodels/tune/pull/778
> Updates for tune#778

- tests/testthat/_snaps/survival-fit-resamples.md
Related to tidymodels/tune#814.
> fix typo in eval time warning

- tests/testthat/_snaps/survival-tune-show-best.md
- tests/testthat/_snaps/survival-tune_race_win_loss.md
- tests/testthat/test-survival-tune_race_win_loss.R
Testing for https://github.com/tidymodels/finetune/pull/98 🐛
> test metric checking in `show_best.tune_race()`

- .github/workflows/GH-R-CMD-check.yaml
> use dev tune for GH check

- tests/testthat/test-parsnip-survival-censoring-weights.R
Closes #167. :) This line was added yesterday so I'm assuming the intended version is current dev.
Tests will fail until #171 is resolved.
> bump workflows version in skip

- .github/workflows/GH-R-CMD-check.yaml
> correct finetune ref

- tests/testthat/_snaps/survival-fit-resamples.md
- tests/testthat/_snaps/survival-tune-bayes.md
- tests/testthat/_snaps/survival-tune-eval-time-attribute.md
- tests/testthat/_snaps/survival-tune-grid.md
- tests/testthat/_snaps/survival-tune-sa.md
- tests/testthat/_snaps/survival-tune-select.md
- tests/testthat/_snaps/survival-tune_race_anova.md
- tests/testthat/_snaps/survival-tune_race_win_loss.md
```
pak::pak(
paste0("tidymodels/", c("parsnip", "censored", "workflows", "yardstick", "tune", "finetune"))
)
```
and
```
devtools::test(filter = "(survival)|(censor)")
```
> Update survival snapshots

- DESCRIPTION
> Use CRAN version of aorsf

- tests/testthat/_snaps/survival-tune-select.md
- tests/testthat/test-survival-tune-select.R
Updates for https://github.com/tidymodels/tune/pull/826
> update snapshots for tune#826

- tests/testthat/_snaps/survival-augment.md
- tests/testthat/test-survival-augment.R
Needed for https://github.com/tidymodels/parsnip/pull/1058
> update snapshot for parsnip 1058

- tests/testthat/_snaps/survival-workflow-set.md
- tests/testthat/test-survival-workflow-set.R
> test `workflow_set()` and `workflow_map()` for survival models

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/survival-tune-autoplot.md
- tests/testthat/test-survival-tune-autoplot.R
> autoplot survival tests

- .github/workflows/GH-R-CMD-check.yaml
- DESCRIPTION
- tests/testthat/_snaps/survival-tune-autoplot.md
- tests/testthat/test-survival-tune-autoplot.R
additional tests for tidymodels/tune#706 and tidymodels/tune#837
> Better warning in autoplot() for unneeded evaluation time 

- DESCRIPTION
- tests/testthat/test-survival-tune-compute-metrics.R
Closes #170
AFAICT there are fairness metrics for survival models.  These tests check that the function works for standard survival metrics.
> unit tests for survival models and compute_metrics

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/test-survival-tune-grid.R
- tests/testthat/test-survival-tune_race_anova.R
- tests/testthat/test-survival-tune_race_win_loss.R
Related to tidymodels/tune#839.
> test new `collect_metrics()` argument to pivot output

- .github/workflows/GH-R-CMD-check.yaml
- tests/testthat/_snaps/survival-fit-resamples.md
- tests/testthat/_snaps/survival-tune-autoplot.md
- tests/testthat/_snaps/survival-tune-select.md
- tests/testthat/_snaps/survival-tune-show-best.md
- tests/testthat/_snaps/survival-tune_race_anova.md
- tests/testthat/_snaps/survival-tune_race_win_loss.md
- tests/testthat/test-survival-fit-resamples.R
- tests/testthat/test-survival-tune-autoplot.R
- tests/testthat/test-survival-tune-select.R
- tests/testthat/test-survival-tune-show-best.R
- tests/testthat/test-survival-tune_race_anova.R
- tests/testthat/test-survival-tune_race_win_loss.R
updates for https://github.com/tidymodels/tune/pull/847
> Update snapshots for "eval_time not needed" warnings

- tests/testthat/test-stacks-tuning.R
Feller was slowwww!
Much easier to run locally now.
> make stacks tuning tests run faster

- tests/testthat/test-engine-parameters-c5.R
- tests/testthat/test-engine-parameters-earth.R
- tests/testthat/test-engine-parameters-randomForest.R
- tests/testthat/test-engine-parameters-ranger.R
can be merged prior to  tidymodels/tune#859
> add brier score to default classification metrics

- tests/testthat/_snaps/survival-tune_race_anova.md
- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
- tests/testthat/test-glmnet-poisson.R
Closes #209, related to tidymodels/parsnip#1078. :)
> skip snapshots with `glue()` error on R 4.3.3+

- tests/testthat/test-parsnip-survival-censoring-weights.R
- tests/testthat/test-survival-tune-grid.R
- tests/testthat/test-survival-tune-show-best.R
- tests/testthat/test-survival-tune_race_anova.R
- tests/testthat/test-survival-tune_race_win_loss.R
> namespace `slice()`

- tests/testthat/test-mars-tuning.R
> `grid_latin_hypercube()` -> `grid_space_filling()`

- tests/testthat/_snaps/recipes1.1.0.9000/recipes-nnmf_sparse.md
> add missing snapshot

- inst/WORDLIST
- tests/testthat/_snaps/glmnet-linear.md
- tests/testthat/_snaps/glmnet-logistic.md
- tests/testthat/_snaps/glmnet-multinom.md
- tests/testthat/_snaps/glmnet-poisson.md
- tests/testthat/test-glmnet-linear.R
- tests/testthat/test-glmnet-logistic.R
- tests/testthat/test-glmnet-multinom.R
- tests/testthat/test-glmnet-poisson.R
changes from tidymodels/parsnip#1214
> call routing in parsnip

- tests/testthat/_snaps/sparsity.md
- tests/testthat/test-sparsity.R
To close: https://github.com/tidymodels/extratests/issues/229
Follows the instructions in #229
> Add workflow sparsity testing

- tests/testthat/_snaps/parsnip-model-formula.md
> Fix logging of (parsnip) error

- tests/testthat/_snaps/tune-catalog-finetune.md
- tests/testthat/test-tune-catalog-finetune.R
to close https://github.com/tidymodels/extratests/issues/246
Related to https://github.com/tidymodels/tune/issues/1074
> set allow_par = TRUE in catalog-finetune

- tests/testthat/_snaps/survival-tune-autoplot.md
Appears to not have been updated in related to https://github.com/tidymodels/extratests/commit/bce6affc866b4d7f2b1852459fabafcb76e00550
> update more snapshot updates related to get_labs()
